M48
; DRILL file {KiCad 9.0.5} date 2025-11-15T09:05:51-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-15T09:05:51-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X161.7Y-101.85
X161.7Y-110.65
T2
X114.42Y-54.43
X114.42Y-83.64
X165.22Y-54.43
X165.22Y-83.64
M30
