M48
; DRILL file {KiCad 9.0.5} date 2025-11-09T16:01:58-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-09T16:01:58-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X176.84Y-84.17
T2
X175.95Y-122.35
X175.95Y-131.15
T3
X133.532Y-47.33
X133.532Y-76.54
X184.332Y-47.33
X184.332Y-76.54
M30
